# This rule is not used by the project portal-expose itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to portal.portal.gosuda.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: portal-expose
    app.kubernetes.io/managed-by: kustomize
  name: portalexpose-viewer-role
rules:
- apiGroups:
  - portal.portal.gosuda.org
  resources:
  - portalexposes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - portal.portal.gosuda.org
  resources:
  - portalexposes/status
  verbs:
  - get
